### ISSUE TITLE
Anonymous comments with default Gravatar images.

### ISSUE THREAD

**Issue by HLFH** [fiddur/some-comments#1]
Hi,

I believe anonymous comments could be great (you have just to put your name and your email). 

Then with the comment, you get get a default gravatar image : https://en.gravatar.com/site/implement/images/

Thanks in advance,

**Comment by fiddur** [comment]
I guess that would require some spam-bot stopping measures?

It would be easy to add as an option, so why not :)

**Comment by HLFH** [comment]
Yes, it could require some spam-bot stopping measures with reCAPTCHA for example: https://jaxbot.me/articles/new-nocaptcha-recaptcha-with-node-js-express-12-9-2014

**Comment by fiddur** [comment]
I'm thiking about adding a simple moderated system, so the site admin could accept or delete (or set the default to accept and be able to delete by hand).  There are still many spam-bots that won't recognize the js-generated input anyway :)

Then some external captcha service could be added at a later point...

**Comment by HLFH** [comment]
Yes, a simple moderated system is really great. I agree with you, the issue will be created when some external captcha service will be **necessary** against spam-bots, and the necessity is not effective right now. So, a simple anonymous-like moderated system will be a great pleasure :)

**Comment by HLFH** [comment]
Any updates? ;)

**Comment by fiddur** [comment]
Looking at it now, after the db-migrations and fixups that are in develop-branch now.  (No migrations from 0.1.0 though…)

Since all comments expect to be connected to a user, I think I will add the possibility to auto-create a user that you get logged in as for the rest of the session, storing the IP there and having a unique user id.  That way, you get a unique gravatar (including id in hash) and you might be able to edit/delete your own comments until you log out (or end the cookie session).

**Comment by HLFH** [comment]
@fiddur Thank you so much ;)

**Comment by fiddur** [comment]
This is now in 0.2.0.  Try it and open a bug if it doesn't work as expected!
