### ISSUE TITLE
Email subscription with Nodemailer

### ISSUE THREAD

**Issue by HLFH** [fiddur/some-comments#2]
Hi,

When somebody comments a post, he gives to the commenting system his email and his name.
So, when another guy comments after him, the first guy should receive an email with the content of the next comment. This email subscription could be built with Nodemailer because Nodemailer is shipped within Ghost.

Thanks in advance,

**Comment by fiddur** [comment]
Thank's for the tip.  I haven't started looking into mail-handling in node yet, now I have a starting place.

**Comment by HLFH** [comment]
For example, if you want a contact form using Ghost and Nodemailer, the best way is: http://tarikk.com/ghost-blog-contact-form-using-ghosts-nodemailer/

**Comment by fiddur** [comment]
This is run as a separate server, so it doesn't share any code with Ghost, but I can use the same lib, if it's a good one.

My choice was to code it as a standalone single purpose server that can be used alongside ghost, other blogs or even a static web page.  That's why it's linked into the theme with just javascript.

**Comment by fiddur** [comment]
I've added nodemailer with very simple notifications in develop-branch, preparing to release it as 0.2.0.  Unfortunately, it's not backwards compatible, since it requires the pages canonical URLs rather than just a page identifier.

I won't release this until there is an unsubscribe endpoint though, but you could try it out.

**Comment by HLFH** [comment]
@fiddur Thanks a lot!!! With a kind of [anonymous commenting with email](http://feedback.uservoice.com/knowledgebase/articles/89984-can-i-enable-anonymous-feedback), Some Comments will be on top!!

**Comment by fiddur** [comment]
I have some more refactoring I plan to do before releasing 0.2.  I realised I mixed the ORM classes to much into the application logic, when I should have held kept that in the models.  Roughly, I think 0.2 could be out in a week or two (with migration from 0.1), and then I hope to make some design and user/admin pages over the summer.

**Comment by HLFH** [comment]
Yes, I also saw that there were some issues with the ORM classes. Good luck! You rock!

**Comment by fiddur** [comment]
This is now in 0.2.0.  Try it and open a bug if it doesn't work as expected!
